// ════════════════════════════════════════
// Hero Party — Card & Game Metadata
// ════════════════════════════════════════

export const CARDS = {
  cursedItems: [
    {id:'ci1', name:"Curse of the Snake's Eyes", type:'Cursed Item', effect:"Each time you roll to use the equipped Hero card's effect, -2 to your roll.", qty:2},
    {id:'ci2', name:"Sealing Key", type:'Cursed Item', effect:"You cannot use the equipped Hero card's effect.", qty:1},
    {id:'ci3', name:"Suspiciously Shiny Coin", type:'Cursed Item', effect:"If you successfully roll to use the equipped Hero card's effect, DISCARD a card.", qty:1},
  ],
  heroes: [
    // Bard
    {id:'hb1',name:'Dodgy Dealer',type:'Hero: Bard',roll:9,effect:'Trade hands with another player.',qty:1},
    {id:'hb2',name:'Fuzzy Cheeks',type:'Hero: Bard',roll:8,effect:'DRAW a card and play a Hero card from your hand immediately.',qty:1},
    {id:'hb3',name:'Greedy Cheeks',type:'Hero: Bard',roll:8,effect:'Each other player must give you a card from their hand.',qty:1},
    {id:'hb4',name:'Lucky Bucky',type:'Hero: Bard',roll:7,effect:"Pull a card from another player's hand. If that card is a Hero card, you may play it immediately.",qty:1},
    {id:'hb5',name:'Mellow Dee',type:'Hero: Bard',roll:7,effect:'DRAW a card. If that card is a Hero card, you may play it immediately.',qty:1},
    {id:'hb6',name:'Napping Nibbles',type:'Hero: Bard',roll:2,effect:'Do nothing.',qty:1},
    {id:'hb7',name:'Peanut',type:'Hero: Bard',roll:7,effect:'DRAW 2 cards.',qty:1},
    {id:'hb8',name:'Tipsy Tootie',type:'Hero: Bard',roll:6,effect:"Choose a player. STEAL a Hero card from that player's Party and move Tipsy Tootie to that player's Party.",qty:1},
    // Fighter
    {id:'hf1',name:'Bad Axe',type:'Hero: Fighter',roll:8,effect:'DESTROY a Hero card.',qty:1},
    {id:'hf2',name:'Bear Claw',type:'Hero: Fighter',roll:7,effect:"Pull a card from another player's hand. If it is a Hero card, pull a second card from that player's hand.",qty:1},
    {id:'hf3',name:'Beary Wise',type:'Hero: Fighter',roll:7,effect:'Each other player must DISCARD a card. Choose one of the discarded cards and add it to your hand.',qty:1},
    {id:'hf4',name:'Fury Knuckle',type:'Hero: Fighter',roll:5,effect:"Pull a card from another player's hand. If it is a Challenge card, pull a second card from that player's hand.",qty:1},
    {id:'hf5',name:'Heavy Bear',type:'Hero: Fighter',roll:5,effect:'Choose a player. That player must DISCARD 2 cards.',qty:1},
    {id:'hf6',name:'Pan Chucks',type:'Hero: Fighter',roll:8,effect:'DRAW 2 cards. If at least one of those cards is a Challenge card, you may reveal it, then DESTROY a Hero card.',qty:1},
    {id:'hf7',name:'Qi Bear',type:'Hero: Fighter',roll:10,effect:'DISCARD up to 3 cards. For each card discarded, DESTROY a Hero card.',qty:1},
    {id:'hf8',name:'Tough Teddy',type:'Hero: Fighter',roll:4,effect:'Each other player with a Fighter in their Party must DISCARD a card.',qty:1},
    // Guardian
    {id:'hg1',name:'Calming Voice',type:'Hero: Guardian',roll:9,effect:"Hero cards in your Party cannot be stolen until your next turn.",qty:1},
    {id:'hg2',name:'Guiding Light',type:'Hero: Guardian',roll:7,effect:'Search the discard pile for a Hero card and add it to your hand.',qty:1},
    {id:'hg3',name:'Holy Curselifter',type:'Hero: Guardian',roll:5,effect:"Return a Cursed Item card equipped to a Hero card in your Party to your hand.",qty:1},
    {id:'hg4',name:'Iron Resolve',type:'Hero: Guardian',roll:8,effect:"Cards you play cannot be challenged for the rest of your turn.",qty:1},
    {id:'hg5',name:'Mighty Blade',type:'Hero: Guardian',roll:8,effect:"Hero cards in your Party cannot be destroyed until your next turn.",qty:1},
    {id:'hg6',name:'Radiant Horn',type:'Hero: Guardian',roll:6,effect:'Search the discard pile for a Modifier card and add it to your hand.',qty:1},
    {id:'hg7',name:'Vibrant Glow',type:'Hero: Guardian',roll:9,effect:'+5 to all of your rolls until the end of your turn.',qty:1},
    {id:'hg8',name:'Wise Shield',type:'Hero: Guardian',roll:6,effect:'+3 to all of your rolls until the end of your turn.',qty:1},
    // Ranger
    {id:'hr1',name:'Bullseye',type:'Hero: Ranger',roll:7,effect:'Look at the top 3 cards of the deck. Add one to your hand, then return the other two to the top of the deck in any order.',qty:1},
    {id:'hr2',name:'Hook',type:'Hero: Ranger',roll:6,effect:'Play an Item card from your hand immediately and DRAW a card.',qty:1},
    {id:'hr3',name:'Lookie Rookie',type:'Hero: Ranger',roll:5,effect:'Search the discard pile for an Item card and add it to your hand.',qty:1},
    {id:'hr4',name:'Quick Draw',type:'Hero: Ranger',roll:8,effect:'DRAW 2 cards. If at least one of those cards is an Item card, you may play one of them immediately.',qty:1},
    {id:'hr5',name:'Serious Grey',type:'Hero: Ranger',roll:9,effect:'DESTROY a Hero card and DRAW a card.',qty:1},
    {id:'hr6',name:'Sharp Fox',type:'Hero: Ranger',roll:5,effect:"Look at another player's hand.",qty:1},
    {id:'hr7',name:'Wildshot',type:'Hero: Ranger',roll:8,effect:'DRAW 3 cards and DISCARD a card.',qty:1},
    {id:'hr8',name:'Wily Red',type:'Hero: Ranger',roll:10,effect:'DRAW cards until you have 7 cards in your hand.',qty:1},
    // Thief
    {id:'ht1',name:'Kit Napper',type:'Hero: Thief',roll:9,effect:'STEAL a Hero card.',qty:1},
    {id:'ht2',name:'Meowzio',type:'Hero: Thief',roll:10,effect:"Choose a player. STEAL a Hero card from that player's Party and pull a card from that player's hand.",qty:1},
    {id:'ht3',name:'Plundering Puma',type:'Hero: Thief',roll:6,effect:"Pull 2 cards from another player's hand. That player may DRAW a card.",qty:1},
    {id:'ht4',name:'Shurikitty',type:'Hero: Thief',roll:9,effect:'DESTROY a Hero card. If that Hero card had an Item card equipped to it, add that Item card to your hand instead of moving it to the discard pile.',qty:1},
    {id:'ht5',name:'Silent Shadow',type:'Hero: Thief',roll:8,effect:"Look at another player's hand. Choose a card and add it to your hand.",qty:1},
    {id:'ht6',name:'Slippery Paws',type:'Hero: Thief',roll:6,effect:"Pull 2 cards from another player's hand, then DISCARD one of those cards.",qty:1},
    {id:'ht7',name:'Sly Pickings',type:'Hero: Thief',roll:6,effect:"Pull a card from another player's hand. If that card is an Item card, you may play it immediately.",qty:1},
    {id:'ht8',name:'Smooth Mimimeow',type:'Hero: Thief',roll:7,effect:"Pull a card from the hand of each other player with a Thief in their Party.",qty:1},
    // Wizard
    {id:'hw1',name:'Bun Bun',type:'Hero: Wizard',roll:5,effect:'Search the discard pile for a Magic card and add it to your hand.',qty:1},
    {id:'hw2',name:'Buttons',type:'Hero: Wizard',roll:6,effect:"Pull a card from another player's hand. If it is a Magic card, you may play it immediately.",qty:1},
    {id:'hw3',name:'Fluffy',type:'Hero: Wizard',roll:10,effect:'DESTROY 2 Hero cards.',qty:1},
    {id:'hw4',name:'Hopper',type:'Hero: Wizard',roll:7,effect:'Choose a player. That player must SACRIFICE a Hero card.',qty:1},
    {id:'hw5',name:'Snowball',type:'Hero: Wizard',roll:6,effect:'DRAW a card. If it is a Magic card, you may play it immediately and DRAW a second card.',qty:1},
    {id:'hw6',name:'Spooky',type:'Hero: Wizard',roll:10,effect:'Each other player must SACRIFICE a Hero card.',qty:1},
    {id:'hw7',name:'Whiskers',type:'Hero: Wizard',roll:11,effect:'STEAL a Hero card and DESTROY a Hero card.',qty:1},
    {id:'hw8',name:'Wiggles',type:'Hero: Wizard',roll:10,effect:'STEAL a Hero card and roll to use its effect immediately.',qty:1},
  ],
  items: [
    {id:'it1',name:'Bard Mask',type:'Item',effect:'The equipped Hero card is considered a Bard instead of its original class.',qty:1},
    {id:'it2',name:'Decoy Doll',type:'Item',effect:'If the equipped Hero card would be sacrificed or destroyed, move Decoy Doll to the discard pile instead.',qty:1},
    {id:'it3',name:'Fighter Mask',type:'Item',effect:'The equipped Hero card is considered a Fighter instead of its original class.',qty:1},
    {id:'it4',name:'Guardian Mask',type:'Item',effect:'The equipped Hero card is considered a Guardian instead of its original class.',qty:1},
    {id:'it5',name:'Particularly Rusty Coin',type:'Item',effect:"If you unsuccessfully roll to use the equipped Hero card's effect, DRAW a card.",qty:2},
    {id:'it6',name:'Ranger Mask',type:'Item',effect:'The equipped Hero card is considered a Ranger instead of its original class.',qty:1},
    {id:'it7',name:'Really Big Ring',type:'Item',effect:"Each time you roll to use the equipped Hero card's effect, +2 to your roll.",qty:2},
    {id:'it8',name:'Thief Mask',type:'Item',effect:'The equipped Hero card is considered a Thief instead of its original class.',qty:1},
    {id:'it9',name:'Wizard Mask',type:'Item',effect:'The equipped Hero card is considered a Wizard instead of its original class.',qty:1},
  ],
  magic: [
    {id:'mg1',name:'Call to the Fallen',type:'Magic',effect:'Search the discard pile for a Hero card and add it to your hand.',qty:1},
    {id:'mg2',name:'Critical Boost',type:'Magic',effect:'DRAW 3 cards and DISCARD a card.',qty:2},
    {id:'mg3',name:'Destructive Spell',type:'Magic',effect:'DISCARD a card, then DESTROY a Hero card.',qty:2},
    {id:'mg4',name:'Enchanted Spell',type:'Magic',effect:'+2 to all of your rolls until the end of your turn.',qty:2},
    {id:'mg5',name:'Entangling Trap',type:'Magic',effect:'DISCARD 2 cards, then STEAL a Hero card.',qty:2},
    {id:'mg6',name:'Forced Exchange',type:'Magic',effect:"Choose a player. STEAL a Hero card from that player's Party, then move a Hero card from your Party to that player's Party.",qty:1},
    {id:'mg7',name:'Forceful Winds',type:'Magic',effect:"Return every equipped Item card to its respective player's hand.",qty:1},
    {id:'mg8',name:'Winds of Change',type:'Magic',effect:"Return an Item card equipped to any player's Hero card to that player's hand, then DRAW a card.",qty:2},
  ],
  modifiers: [
    {id:'mod1',name:'MODIFIER 0i4',type:'Modifier',effect:'Play this card after any player (including you) rolls the dice. -4 to that roll.',bonus:4,penalty:-4,qty:4},
    {id:'mod2',name:'MODIFIER 1i3',type:'Modifier',effect:'Play this card after any player (including you) rolls the dice. +1 or -3 to that roll.',bonus:1,penalty:-3,qty:4},
    {id:'mod3',name:'MODIFIER 2i2',type:'Modifier',effect:'Play this card after any player (including you) rolls the dice. +2 or -2 to that roll.',bonus:2,penalty:-2,qty:9},
    {id:'mod4',name:'MODIFIER 3i1',type:'Modifier',effect:'Play this card after any player (including you) rolls the dice. +3 or -1 to that roll.',bonus:3,penalty:-1,qty:4},
    {id:'mod5',name:'MODIFIER 4i0',type:'Modifier',effect:'Play this card after any player (including you) rolls the dice. +4 to that roll.',bonus:4,penalty:0,qty:4},
  ],
  challenges: [
    {id:'ch1',name:'CHALLENGE',type:'Challenge',effect:'You may play this card when another player attempts to play a Hero, Item, or Magic card. CHALLENGE that card.',qty:14},
  ],
  monsters: [
    {id:'mn1', name:'Abyss Queen',       type:'Monster', require:'HH',   loseRoll:5, loseEffect:'SACRIFICE a Hero card',  winRoll:8,  winEffect:'SLAY this Monster card',           passiveEffect:"Each time another player plays a Modifier card on one of your rolls, +1 to your roll."},
    {id:'mn2', name:'Anuran Cauldron',   type:'Monster', require:'HHH',  loseRoll:6, loseEffect:'SACRIFICE a Hero card',  winRoll:7,  winEffect:'SLAY this Monster card',           passiveEffect:'Each time you roll, +1 to your roll.'},
    {id:'mn3', name:'Arctic Aries',      type:'Monster', require:'H',    loseRoll:6, loseEffect:'SACRIFICE a Hero card',  winRoll:10, winEffect:'SLAY this Monster card',           passiveEffect:"Each time you successfully roll to use a Hero card's effect, you may DRAW a card."},
    {id:'mn4', name:'Bloodwing',         type:'Monster', require:'HH',   loseRoll:6, loseEffect:'SACRIFICE a Hero card',  winRoll:9,  winEffect:'SLAY this Monster card',           passiveEffect:'Each time another player CHALLENGES you, that player must DISCARD a card.'},
    {id:'mn5', name:'Corrupted Sabretooth', type:'Monster', require:'HHH', loseRoll:6, loseEffect:'SACRIFICE a Hero card', winRoll:9, winEffect:'SLAY this Monster card & DRAW a card', passiveEffect:'Each time you would DESTROY a Hero card, you may STEAL that Hero card instead.'},
    {id:'mn6', name:'Crowned Serpent',   type:'Monster', require:'HH',   loseRoll:7, loseEffect:'SACRIFICE a Hero card',  winRoll:10, winEffect:'SLAY this Monster card',           passiveEffect:'Each time any player (including you) plays a Modifier card, you may DRAW a card.'},
    {id:'mn7', name:'Dark Dragon King',  type:'Monster', require:'BH',   loseRoll:4, loseEffect:'DISCARD 2 cards',        winRoll:8,  winEffect:'SLAY this Monster card',           passiveEffect:"Each time you roll for a Hero card's effect, +1 to your roll."},
    {id:'mn8', name:'Dracos',            type:'Monster', require:'H',    loseRoll:5, loseEffect:'SLAY this Monster card', winRoll:8,  winEffect:'SACRIFICE a Hero card',            passiveEffect:'Each time a Hero card in your Party is destroyed, you may DRAW a card.'},
    {id:'mn9', name:'Malamammoth',       type:'Monster', require:'RH',   loseRoll:4, loseEffect:'DISCARD 2 cards',        winRoll:8,  winEffect:'SLAY this Monster card',           passiveEffect:'Each time you DRAW an Item card, you may play it immediately.'},
    {id:'mn10',name:'Mega Slime',        type:'Monster', require:'HHHH', loseRoll:7, loseEffect:'SACRIFICE a Hero card',  winRoll:8,  winEffect:'SLAY this Monster card & DRAW 2 cards', passiveEffect:'You may spend an extra action point on each of your turns.'},
    {id:'mn11',name:'Orthus',            type:'Monster', require:'WH',   loseRoll:4, loseEffect:'DISCARD 2 cards',        winRoll:8,  winEffect:'SLAY this Monster card',           passiveEffect:'Each time you DRAW a Magic card, you may play it immediately.'},
    {id:'mn12',name:'Rex Major',         type:'Monster', require:'GH',   loseRoll:4, loseEffect:'DISCARD 2 cards',        winRoll:8,  winEffect:'SLAY this Monster card',           passiveEffect:'Each time you DRAW a Modifier card, you may reveal it and DRAW a second card.'},
    {id:'mn13',name:'Terratuga',         type:'Monster', require:'H',    loseRoll:7, loseEffect:'SACRIFICE a Hero card',  winRoll:11, winEffect:'SLAY this Monster card',           passiveEffect:'Your Hero cards cannot be destroyed.'},
    {id:'mn14',name:'Titan Wyvern',      type:'Monster', require:'FH',   loseRoll:4, loseEffect:'DISCARD 2 cards',        winRoll:8,  winEffect:'SLAY this Monster card',           passiveEffect:'Each time you roll for a Challenge card, +1 to your roll.'},
    {id:'mn15',name:'Warworn Owlbear',   type:'Monster', require:'TH',   loseRoll:4, loseEffect:'DISCARD 2 cards',        winRoll:8,  winEffect:'SLAY this Monster card',           passiveEffect:'Item cards you play cannot be challenged.'},
  ],
  partyLeaders: [
    {id:'pl1',name:'The Charismatic Song', type:'Party Leader: Bard',     effect:"Each time you roll to use a Hero card's effect, +1 to your roll."},
    {id:'pl2',name:'The Cloaked Sage',     type:'Party Leader: Wizard',   effect:'Each time you play a Magic card, DRAW a card.'},
    {id:'pl3',name:'The Divine Arrow',     type:'Party Leader: Ranger',   effect:'Each time you roll to ATTACK a Monster card, +1 to your roll.'},
    {id:'pl4',name:'The Fist of Reason',   type:'Party Leader: Fighter',  effect:'Each time you roll to CHALLENGE, +2 to your roll.'},
    {id:'pl5',name:'The Protecting Horn',  type:'Party Leader: Guardian', effect:'Each time you play a Modifier card on a roll, +1 or -1 to that roll.'},
    {id:'pl6',name:'The Shadow Claw',      type:'Party Leader: Thief',    effect:"Once per turn on your turn, you may spend an action point to pull a card from another player's hand."},
  ],
};
